# Generated by Django 4.1.7 on 2023-03-31 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('uid', models.AutoField(primary_key=True, serialize=False)),
                ('hospital', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('yesno', models.CharField(max_length=3)),
                ('place', models.CharField(max_length=50)),
                ('wardno', models.IntegerField()),
                ('phone', models.IntegerField()),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('name', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
    ]
