# Generated by Django 4.0.4 on 2023-05-11 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('macares', '0003_remove_user_hospital_user_ashaid'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bg',
            field=models.CharField(default='A+', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='lastmen',
            field=models.DateField(default='2002-02-01'),
        ),
        migrations.AddField(
            model_name='user',
            name='lastpg',
            field=models.DateField(default='2002-02-01'),
        ),
        migrations.AlterField(
            model_name='user',
            name='age',
            field=models.IntegerField(default='10'),
        ),
    ]
