# Generated by Django 4.0.4 on 2023-05-11 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('macares', '0004_user_bg_user_lastmen_user_lastpg_alter_user_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='lastmen',
            field=models.DateField(default='2002-02-01', verbose_name='N j, Y'),
        ),
        migrations.AlterField(
            model_name='user',
            name='lastpg',
            field=models.DateField(default='2002-02-01', verbose_name='N j, Y'),
        ),
    ]
