# Generated by Django 4.0.4 on 2023-05-11 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('macares', '0005_alter_user_lastmen_alter_user_lastpg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='lastmen',
            field=models.DateField(default='2002-02-01', verbose_name='Y-m-d'),
        ),
        migrations.AlterField(
            model_name='user',
            name='lastpg',
            field=models.DateField(default='2002-02-01', verbose_name='Y-m-d'),
        ),
    ]
