# Generated by Django 4.1.7 on 2023-06-07 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('macares', '0006_alter_user_lastmen_alter_user_lastpg'),
    ]

    operations = [
        migrations.CreateModel(
            name='Month',
            fields=[
                ('uid', models.IntegerField()),
                ('mid', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='rchid',
            field=models.IntegerField(default='0'),
        ),
    ]
